name: chewie
description: A video player for Flutter with Cupertino and Material play controls

version: 1.3.2
homepage: https://github.com/hmukwana/chewie

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter
  cast: ^1.1.1
  cupertino_icons: ^1.0.3
  flutter_mdns_plugin: ^0.0.3
  mime: ^1.0.0
  observable: ^0.23.0
  universal_io: ^2.0.4
  provider: ^6.0.1
  video_player: ^2.2.7
  wakelock: ^0.6.1+1
  very_good_analysis: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.7.2

flutter:
  uses-material-design: true

  assets:
    - assets/castIcon/
